spring:
  datasource-data:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  datasource-meta:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${META_DB_DATABASE}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${META_DB_USERNAME}
    password: ${META_DB_PASSWORD}

  batch:
    jdbc:
      initialize-schema: always
    job:
      name: ${job.name:NONE}
      enabled: false

server:
  port: 8081
