services:
  db:
    restart: always
    image: mariadb
    ports:
      - 13306:3306
    env_file: ~/Projects/wordApp/app/.env
    environment:
      TZ: Asia/Seoul
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
  redis:
    image: my-redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
#      - ./docker/redis/dump.rdb:/usr/local/etc/redis/dump.rdb
    command: /usr/local/bin/redis-server /usr/local/etc/redis/redis.conf