### 회원가입
POST localhost:8088/user/signup
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "asdfghjkl1!",
  "nickname": "test",
  "profileImagePath": "/data/images/asdf.png"
}

### 비밀번호 변경
PUT localhost:8088/user/pw
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "oldPassword": "asdfghjkl1!",
  "newPassword": "asdfghjkl2!"
}

### 비밀번호 변경
PUT localhost:8088/user/pw
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "oldPassword": "asdfghjkl2!",
  "newPassword": "asdfghjkl1!"
}

### 회원정보 출력
GET localhost:8088/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 회원정보 수정
PUT localhost:8088/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "nickname": "abc",
  "profileImagePath": "f349d273-13cd-462e-9ae4-fa7f18130a97"
}

### 회원 탈퇴
DELETE localhost:8088/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}
