### 단어 저장
POST localhost:8088/word/EN
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "word": "Pneumonoultramicroscopicsilicovolcanoconiosis",
  "mean": "mean",
  "read": "read",
  "memo": "memo",
  "memorization": "N",
  "details": [{
    "wordGroupId": 24,
    "title": "title1",
    "content": "content1"
  }, {
    "wordGroupId": 1,
    "title": "title2",
    "content": "content2"
  }, {
    "wordGroupId": 3,
    "title": "title3",
    "content": "content3"
  }]
}

> {%
    client.global.set("wordId", response.body.wordId)
%}

### 단어 조회
GET localhost:8088/word?current=0
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 단어 검색
GET localhost:8088/word?current=0&searchText=word
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 단어 조회 - 암기 여부
GET localhost:8088/word?current=1&memorization=N
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 단어 조회 - 언어
GET localhost:8088/word?current=1&lang=EN
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 단어 수정
PUT localhost:8088/word/all/{{wordId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "mean": "meanUpdate",
  "read": "readUpdate",
  "memo": "memoUpdate",
  "memorization": "N",
  "details": [{
    "wordDetailId": 18,
    "wordGroupId": 1,
    "title": "title1Update",
    "content": "content1Update"
  }, {
    "wordDetailId": 23,
    "wordGroupId": 1,
    "title": "title2Update",
    "content": "content2Update"
  }, {
    "wordDetailId": 24,
    "wordGroupId": 1,
    "title": "title3Update",
    "content": "content3Update"
  }]
}

### 단어 수정 - 메모
PUT localhost:8088/word/memo/{{wordId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "memo": "memoUpdate1"
}

### 단어 수정 - 암기 여부
PUT localhost:8088/word/memorization/{{wordId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "memorization": "Y"
}

### 단어장 이동
PUT localhost:8088/word/{{wordId}}/folder/6
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### 단어 삭제
DELETE localhost:8088/word/{{wordId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}
