spring:
  profiles:
    include: [oauth2, mail, meta]
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        auto_quote_keyword: true
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

  datasource:
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    jdbc-url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?characterEncoding=UTF-8&serverTimezone=UTC

server:
  servlet:
    context-path: /api
  tomcat:
    mbeanregistry:
      enabled: true
    uri-encoding: UTF-8
  port: 8088
jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALID_TIME}

logging:
  level:
    root: info

cstm:
  processbuilder:
    path: ${PROCESS_BUILDER_PATH}
    program: ${PROCESS_BUILDER_PROGRAM}
  file:
    path: ${FILE_PATH}
  gtts:
    url: ${GTTS_API}
    path: ${GTTS_PATH}


management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  server:
    port: 18088
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"

