### 오늘의 문장 저장
POST {{host}}/daily-sentence
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "sentence": "She was running through the park early in the morning, enjoying the crisp air and the sound of birds chirping, as the first rays of sunlight began to break through the trees.",
  "mean": "그녀는 아침 일찍 공원을 달리고 있었고, 상쾌한 공기와 새들이 지저귀는 소리를 즐기면서, 첫 번째 햇살이 나무들 사이로 비추기 시작했다."
}

> {%
    client.global.set("dailySentenceId", response.body.dailySentenceId)
%}

### 오늘의 문장 전체 조회
GET {{host}}/daily-sentence
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 오늘의 문장 연도 별 조회
GET {{host}}/daily-sentence?year=2024
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 오늘의 문장 월별 조회
GET {{host}}/daily-sentence?year=2024&month=12
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 오늘의 문장 일별 조회
GET {{host}}/daily-sentence?year=2024&month=11&day=26
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 오늘의 문장 주별 조회
GET {{host}}/daily-sentence?year=2024&month=11&week=4
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 오늘의 문장 날짜 리스트 조회
GET {{host}}/daily-sentence/days?year=2024&month=12
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 오늘의 문장 연관 단어 정보 조회
GET {{host}}/daily-sentence/relation/33
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 오늘의 문장 수정 - 뜻
PUT {{host}}/daily-sentence/{{dailySentenceId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "mean": "오늘의 문장 뜻 수정",
  "sentence": null
}

### 오늘의 문장 수정 - 문장과 뜻
PUT {{host}}/daily-sentence/{{dailySentenceId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "sentence": "Without a smartphone, a person would be unable to show this code which would make it difficult for them to enter",
  "mean": "스마트폰이 없으면 사람이 이 코드를 보여줄 수 없어 입장하기가 어렵습니다1."
}

### 오늘의 문장 삭제
DELETE {{host}}/daily-sentence/28
Content-Type: application/json
Authorization: Bearer {{accessToken}}