### 사전 조회
GET {{host}}/dict/stay in shape
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 사전 조회 (자동완성)
GET {{host}}/dict/list/excep
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 사전 조회 (자동완성)
GET {{host}}/dict/list/db/excep
Content-Type: application/json
Authorization: Bearer {{accessToken}}