### 사전 조회
GET localhost:8088/api/dict/stay in shape
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 사전 조회 (자동완성)
GET localhost:8088/api/dict/list/excep
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 사전 조회 (자동완성)
GET localhost:8088/api/dict/list/db/excep
Content-Type: application/json
Authorization: Bearer {{accessToken}}