### 폴더 생성
POST {{host}}/folders
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderName": "folderName",
  "memo": "memo",
  "color": "#fff",
  "background": "#000"
}

> {%
    client.global.set("folderId", response.body.folderId)
%}

### 폴더 조회
GET {{host}}/folders
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 폴더 수정
PUT {{host}}/folders/{{folderId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "folderName": "folderNameUpdate",
  "memo": "memoUpdate",
  "color": "#ffff",
  "background": "#0000"
}

### 폴더 삭제
DELETE {{host}}/folders/{{folderId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 폴더 단건 단어 개수 조회
GET {{host}}/folders/6?memorization=false
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 공유 단어장 조회
GET {{host}}/folders/share
Content-Type: application/json
Authorization: Bearer {{accessToken}}
