### 회원가입 - 인증 코드 발송
POST localhost:8088/api/auth/code/signup
Content-Type: application/json

{
  "email": ""
}

### 회원가입 - 인증 코드 인증
POST localhost:8088/api/auth/code/verify
Content-Type: application/json

{
  "email": "0157942@gmail.com",
  "code": 446554
}

### 회원가입
POST localhost:8088/api/user/signup
Content-Type: application/json

{
  "email": "0157942@gmail.com",
  "password": "asdfghjkl1!",
  "nickname": "test",
  "profileImagePath": "/data/images/asdf.png"
}

### 비밀번호 변경 - 인증 코드 발송
POST localhost:8088/api/auth/code/pw
Content-Type: application/json

{
  "email": "0157942@gmail.com"
}

### 비밀번호 변경 - 인증 코드 인증
POST localhost:8088/api/auth/code/verify
Content-Type: application/json

{
  "email": "0157942@gmail.com",
  "code": 286338
}

### 비밀번호 변경 - 비로그인
PUT localhost:8088/api/user/pw/reset
Content-Type: application/json

{
  "email": "0157942@gmail.com",
  "newPassword": "asdfghjkl1!a"
}

### 비밀번호 변경 - 로그인
PUT localhost:8088/api/user/pw
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "oldPassword": "asdfghjkl1!a",
  "newPassword": "asdfghjkl1!"
}

### 회원정보 출력
GET localhost:8088/api/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 회원정보 수정
PUT localhost:8088/api/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "nickname": "abc",
  "profileImagePath": "f349d273-13cd-462e-9ae4-fa7f18130a97"
}

### 회원 탈퇴
DELETE localhost:8088/api/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 유저 검색
GET localhost:8088/api/user/search?q=
Content-Type: application/json
Authorization: Bearer {{accessToken}}
