### 회원가입 - 인증 코드 발송
POST {{host}}/auth/code/signup
Content-Type: application/json

{
  "email": ""
}

### 회원가입 - 인증 코드 인증
POST {{host}}/auth/code/verify
Content-Type: application/json

{
  "email": "0157942@gmail.com",
  "code": 446554
}

### 회원가입
POST {{host}}/user/signup
Content-Type: application/json

{
  "email": "0157942@gmail.com",
  "password": "asdfghjkl1!",
  "nickname": "test",
  "profileImagePath": "/data/images/asdf.png"
}

### 비밀번호 변경 - 인증 코드 발송
POST {{host}}/auth/code/pw
Content-Type: application/json

{
  "email": "0157942@gmail.com"
}

### 비밀번호 변경 - 인증 코드 인증
POST {{host}}/auth/code/verify
Content-Type: application/json

{
  "email": "0157942@gmail.com",
  "code": 286338
}

### 비밀번호 변경 - 비로그인
PUT {{host}}/user/pw/reset
Content-Type: application/json

{
  "email": "0157942@gmail.com",
  "newPassword": "asdfghjkl1!a"
}

### 비밀번호 변경 - 로그인
PUT {{host}}/user/pw
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "oldPassword": "asdfghjkl1!a",
  "newPassword": "asdfghjkl1!"
}

### 회원정보 출력
GET {{host}}/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 회원정보 수정
PUT {{host}}/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "nickname": "abc",
  "profileImagePath": "f349d273-13cd-462e-9ae4-fa7f18130a97"
}

### 회원 탈퇴
DELETE {{host}}/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 유저 검색
GET {{host}}/user/search?q=
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 유저 온보딩 완료
PATCH {{host}}/user/onboarding/complete
Content-Type: application/json
Authorization: Bearer {{accessToken}}
