### 단어장 생성
POST localhost:8088/api/wordbooks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "name",
  "memo": "memo",
  "color": "#fff",
  "background": "#000"
}

> {%
    client.global.set("wordBookId", response.body.wordBookId)
%}

### 단어장 조회
GET localhost:8088/api/wordbooks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 단어장 수정
PUT localhost:8088/api/wordbooks/{{wordBookId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "folderNameUpdate",
  "memo": "memoUpdate",
  "color": "#ffff",
  "background": "#0000"
}

###
@wordBookId = 34

### 단어장 삭제
DELETE localhost:8088/api/wordbooks/{{wordBookId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 단어장 삭제 - 연관 데이터 삭제
DELETE localhost:8088/api/wordbooks/{{wordBookId}}?removeWords=true
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 단어장 단건 조회
GET localhost:8088/api/wordbooks/{{wordBookId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 공유 단어장 조회
GET localhost:8088/api/wordbooks/share
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 단어장 멤버 추가
POST localhost:8088/api/wordbooks/6/members
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": 13,
  "role": "view"
}

### 단어장 멤버 조회
GET localhost:8088/api/wordbooks/6/members
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 단어장 멤버 권한 변경
PUT localhost:8088/api/wordbooks/6/members/role
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": 13,
  "role": "admin"
}

### 단어장 멤버 삭제
DELETE localhost:8088/api/wordbooks/6/members/16
Content-Type: application/json
Authorization: Bearer {{accessToken}}